set_property IOSTANDARD LVCMOS33 [get_ports {reg_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {selector[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {selector[0]}]
set_property PACKAGE_PIN H17 [get_ports {reg_out[0]}]
set_property PACKAGE_PIN K15 [get_ports {reg_out[1]}]
set_property PACKAGE_PIN J13 [get_ports {reg_out[2]}]
set_property PACKAGE_PIN N14 [get_ports {reg_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property PACKAGE_PIN E3 [get_ports clock]


set_property PACKAGE_PIN M17 [get_ports load]
set_property IOSTANDARD LVCMOS33 [get_ports load]

set_property IOSTANDARD LVCMOS33 [get_ports led]
set_property PACKAGE_PIN V11 [get_ports led]

set_property IOSTANDARD LVCMOS33 [get_ports {reg_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_in[4]}]
set_property PACKAGE_PIN J15 [get_ports {reg_in[0]}]
set_property PACKAGE_PIN L16 [get_ports {reg_in[1]}]
set_property PACKAGE_PIN M13 [get_ports {reg_in[2]}]
set_property PACKAGE_PIN R15 [get_ports {reg_in[3]}]
set_property PACKAGE_PIN R17 [get_ports {reg_in[4]}]
set_property PACKAGE_PIN T18 [get_ports {reg_in[5]}]
set_property PACKAGE_PIN V10 [get_ports {selector[1]}]
set_property PACKAGE_PIN U11 [get_ports {selector[0]}]
